### PR TITLE
Enhancement/refactoring server

### PR DESCRIPTION
**Pull request by d-pettersson**
# What's new

- Split the server file in two: app.ts and server.ts
- App is its own class, server creates a new App instance on startup
- Changed DBHost to DBHOST for compatibility reasons
- Adjusted naming of the backup files

# Testing

- Download / Pull this repository.
- Run `npm i`
- Run `git checkout enhancement/refactoring_server`
- Run `npm run test`

### CODE REVIEW

**Comment by d-pettersson** [comment]
I cannot get the tests to pass - I will rollback and push a new commit. Still with refactoring in mind, but less complicated

**Comment by d-pettersson** [comment]
@5h3rr1ll @Darjusch @jwdotpark please review :)

**Review by 5h3rr1ll — CHANGES_REQUESTED** [review]
Looks good! 👍 BUT: Please rebase ur branch on dev on your local machine and solve possible merge conflicts, before we merge it into dev. 😊

**Review by 5h3rr1ll — APPROVED** [review]
Go! 👍

**Pull request merged**
